import { cookies } from "next/headers";

import "./globals.css";
import Image from "next/image";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/components/app-sidebar";

export const metadata = {
  title: "Anno 1800 Guides",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
        <SidebarProvider
          defaultOpen={defaultOpen}
          open={undefined}
          onOpenChange={undefined}
          className={undefined}
          style={undefined}
        >
          <AppSidebar />
          <SidebarTrigger className="" onClick={undefined} />
          <div className="font-sans grid grid-rows-[20px_1fr_20px] justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-8">
            <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
              {children}
            </main>
            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                <Image
                  aria-hidden
                  src="/apple-touch-icon.png"
                  alt="File icon"
                  width={16}
                  height={16}
                  />
                Learn
              </a>
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                <Image
                  aria-hidden
                  src="/apple-touch-icon.png"
                  alt="Window icon"
                  width={16}
                  height={16}
                  />
                Examples
              </a>
            </footer>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
