import { cookies } from "next/headers";

import "./globals.css";
import Image from "next/image";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import ThemeSwitcher from "@/components/ui/ThemeSwitcher"

import { ThemeProvider } from "@/lib/theme/theme-provider"

export const metadata = {
  title: "Anno 1800 Guides",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <SidebarProvider defaultOpen={defaultOpen}>
        <div className="flex min-h-screen">
          {/* Sidebar vlevo */}
          <AppSidebar />

          {/* Pravá část – obsah */}
          <div className="flex flex-col w-full">
            {/* Top navbar */}
            <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-background">
              <SidebarTrigger />
              <ThemeSwitcher />
            </div>

            {/* Hlavní obsah */}
            <main className="flex-1 p-8">{children}</main>

            {/* Footer */}
            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
              <p className="text-muted-foreground text-sm">Veškerý obsah třetích stran zůstává majetkem jejich původních autorů. Pokud zde naleznete svůj obsah a přejete si jeho odstranění, kontaktujte mě.</p>
              {/* <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                <Image
                  aria-hidden
                  src="/apple-touch-icon.png"
                  alt="Window icon"
                  width={16}
                  height={16}
                  />
                Examples
              </a> */}
            </footer>
          </div>
        </div>
      </SidebarProvider>
    </ThemeProvider>
  </body>
    </html>
  );
}
