import { cookies } from "next/headers"

import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/components/app-sidebar";

export const metadata = {
  title: "Anno 1800 Guides",
  description: "Generated by create next app",
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body>
        <SidebarProvider
          defaultOpen={defaultOpen}
          open={undefined}
          onOpenChange={undefined}
          className={undefined}
          style={undefined}
        >
          <AppSidebar />
          <SidebarTrigger className="" onClick={undefined} />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
